# Generated by Django 4.2.5 on 2023-10-01 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Llamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.DateTimeField(auto_now_add=True)),
                ('resultado', models.CharField(choices=[('cita', 'Cita'), ('nocom', 'No se logra comunicación'), ('noint', 'No interesado'), ('dev', 'Paciente llama de vuelta')], max_length=5)),
                ('comentarios', models.TextField(blank=True)),
                ('asistente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
